# Generated by Django 3.1.2 on 2020-10-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userid', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('delivery_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('billing_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
    ]
