# Generated by Django 3.1.2 on 2020-10-20 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_page.user')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('unit_price', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('expiration_date', models.DateTimeField(default=None)),
                ('image_path', models.CharField(default=None, max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_page.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('completed', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer_page.buyer')),
                ('listing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_page.listing')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyer_page.seller')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer_page.seller'),
        ),
    ]
