# Generated by Django 3.1.2 on 2020-10-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_page', '0003_auto_20201021_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='listing_id',
            new_name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
