# Generated by Django 3.1.2 on 2020-10-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_page', '0005_remove_transactions_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
