# Generated by Django 3.1.2 on 2020-10-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer_page', '0006_auto_20201021_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
